extends:
    - stylelint-config-sass-guidelines
    - stylelint-config-property-sort-order-smacss
plugins:
    - stylelint-scss
rules:
    max-nesting-depth: null
    color-named: null
    selector-max-compound-selectors: null
    selector-no-qualifying-type: null
    selector-class-pattern: null
    order/properties-alphabetical-order: null
    scss/dollar-variable-pattern: null
